<?php

return [
    'nav.dashboard' => 'لوحة التحكم',
    'nav.pos'       => 'نقطة البيع',
    'nav.products'  => 'المنتجات',
    'nav.customers' => 'العملاء',
    'nav.suppliers' => 'الموردون',
    'nav.reports'   => 'التقارير',
    'nav.stock'     => 'المخزون',
    'nav.finance'   => 'المالية',
    'nav.users'     => 'المستخدمون',
    'btn.new'       => 'جديد',
    'btn.delete'    => 'حذف',
    'btn.hold'      => 'تعليق',
    'btn.held_bills'=> 'الفواتير المعلقة',
    'btn.payment'   => 'دفع',
    'pos.no_items'  => 'لا توجد أصناف بعد. اضغط على منتج في الجهة اليمنى لإضافته.',
    'pos.total'     => 'الإجمالي',
    'pos.taxes'     => 'الضرائب',
    'pos.refund'    => 'استرجاع',
    'pos.customer_note' => 'ملاحظة للعميل',
    'pos.internal_note' => 'ملاحظة داخلية',
    'pos.quotation' => 'عرض سعر / طلب',
    'nav.dashboard'          => 'لوحة التحكم',
    'nav.pos'                => 'نقطة البيع',
    'nav.products'           => 'المنتجات',
    'nav.customers'          => 'العملاء',
    'nav.suppliers'          => 'الموردون',
    'nav.reports'            => 'التقارير',
    'nav.sales_report'       => 'تقرير المبيعات',
    'nav.sales_by_product'   => 'المبيعات حسب المنتج',
    'nav.stock'              => 'المخزون',
    'nav.stock_report'       => 'تقرير المخزون',
    'nav.stock_adjustment'   => 'تسوية المخزون',
    'nav.stock_movements'    => 'حركات المخزون',
    'nav.finance'            => 'المالية',
    'nav.payments'           => 'المدفوعات',
    'nav.customer_payments'  => 'مدفوعات العملاء',
    'nav.supplier_payments'  => 'مدفوعات الموردين',
    'nav.balances_ledgers'   => 'الأرصدة والسجلات',
    'nav.customer_balances'  => 'أرصدة العملاء',
    'nav.supplier_balances'  => 'أرصدة الموردين',
    'nav.customer_ledger'    => 'سجل حساب العميل',
    'nav.supplier_ledger'    => 'سجل حساب المورد',
    'nav.users'              => 'المستخدمون',

    'nav.settings'           => 'الإعدادات',
    'nav.pos_settings'       => 'إعدادات نقطة البيع',
    'nav.change_password'    => 'تغيير كلمة المرور',
    'nav.sign_out'           => 'تسجيل الخروج',
    // ... expand as needed ...
];