<?php

return [
    'nav.dashboard' => 'Dashboard',
    'nav.pos'       => 'POS',
    'nav.products'  => 'Products',
    'nav.customers' => 'Customers',
    'nav.suppliers' => 'Suppliers',
    'nav.reports'   => 'Reports',
    'nav.stock'     => 'Stock',
    'nav.finance'   => 'Finance',
    'nav.users'     => 'Users',
    'btn.new'       => 'New',
    'btn.delete'    => 'Delete',
    'btn.hold'      => 'Hold',
    'btn.held_bills'=> 'Held bills',
    'btn.payment'   => 'Payment',
    'pos.no_items'  => 'No items yet. Click a product on the right to add it.',
    'pos.total'     => 'Total',
    'pos.taxes'     => 'Taxes',
    'pos.refund'    => 'Refund',
    'pos.customer_note' => 'Customer Note',
    'pos.internal_note' => 'Internal Note',
    'pos.quotation' => 'Quotation/Order',
    
    'nav.dashboard'          => 'Dashboard',
    'nav.pos'                => 'Point of Sale',
    'nav.products'           => 'Products',
    'nav.customers'          => 'Customers',
    'nav.suppliers'          => 'Suppliers',
    'nav.reports'            => 'Reports',
    'nav.sales_report'       => 'Sales report',
    'nav.sales_by_product'   => 'Sales by product',
    'nav.stock'              => 'Stock',
    'nav.stock_report'       => 'Stock Report',
    'nav.stock_adjustment'   => 'Stock Adjustment',
    'nav.stock_movements'    => 'Stock Movements',
    'nav.finance'            => 'Finance',
    'nav.payments'           => 'Payments',
    'nav.customer_payments'  => 'Customer Payments',
    'nav.supplier_payments'  => 'Supplier Payments',
    'nav.balances_ledgers'   => 'Balances & Ledgers',
    'nav.customer_balances'  => 'Customer Balances',
    'nav.supplier_balances'  => 'Supplier Balances',
    'nav.customer_ledger'    => 'Customer Ledger',
    'nav.supplier_ledger'    => 'Supplier Ledger',
    'nav.users'              => 'Users',

    'nav.settings'           => 'Settings',
    'nav.pos_settings'       => 'POS settings',
    'nav.change_password'    => 'Change password',
    'nav.sign_out'           => 'Sign out',
    // ... add more keys gradually as you touch each page ...
];